import React, { useState } from 'react';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { AnimatePresence } from 'framer-motion';
import useSwr from 'swr';
import useFormRefs from '../components/useFormRefs';

import Header from '../components/header';
import InvoiceForm from '../components/InvoiceForm';
import InvoiceList from '../components/InvoiceList';
import Nav from '../components/nav';

import { InputRefs, formRefsType, PaymentTermsEnum, RefObjectType } from '../components/types';
import type { InvoiceDetails } from '../data/invoice-data';
import { invoiceDataJson } from '../data/invoice-data';
import { newIdTag } from '../components/helpers';

const Home: NextPage = () => {
  const router = useRouter();
  const initialItemCounterState = [
    { id: `itemLog-${Math.floor(Math.random() * 10000)}`, name: '', quantity: '0', price: '0' }
  ];

  const { data: invoiceDataSWR, mutate } = useSwr(invoiceDataJson, (args) => JSON.parse(args), {
    revalidateIfStale: false,
    revalidateOnFocus: false,
    revalidateOnReconnect: false
  });

  const [invoiceFormVisbility, setInvoiceFormVisiblity] = useState(false);
  const [itemCounter, setItemCounter] = useState(initialItemCounterState);

  const { formRefs, handleInput, setHandleInput, detailsInput, setDetailsInput } = useFormRefs();

  const formProps = {
    formRefs,
    saveChanges,
    clearForm,
    unmountForm,
    handleInput,
    setHandleInput,
    invoiceFormVisbility,
    itemCounter,
    setItemCounter,
    detailsInput,
    setDetailsInput
  };

  function mountForm() {
    setInvoiceFormVisiblity(true);
    router.push('/?InvoiceData');
  }

  function unmountForm() {
    setHandleInput((prevState) => {
      const newState = structuredClone(prevState);
      for (const inputRef in newState) {
        const refData: string | undefined = (formRefs as formRefsType)[inputRef as keyof InputRefs]
          ?.current?.value;
        newState[inputRef as keyof InputRefs] = refData || '';
      }
      return newState;
    });
    setInvoiceFormVisiblity(false);
    router.push('/');
  }

  function clearForm() {
    setHandleInput((prevState) => {
      const newState = structuredClone(prevState);
      for (const inputRef in newState) {
        newState[inputRef as keyof InputRefs] = '';
      }
      return newState;
    });
    setDetailsInput({
      date: new Date(),
      paymentTerms: PaymentTermsEnum['Net 1 Day']
    });
    setItemCounter([]);
    setInvoiceFormVisiblity(false);
    router.push('/');
  }

  function saveChanges(options = { draft: false }) {
    const newInvoice: InvoiceDetails = {
      id: newIdTag(),
      createdAt: new Date().toLocaleDateString(),
      paymentDue: detailsInput.date.toLocaleDateString(),
      description: formRefs.projectDescriptionInputRef?.current?.value ?? '',
      paymentTerms: detailsInput.paymentTerms,
      sender: {
        city: formRefs.cityInputRef.current?.value ?? '',
        country: formRefs.clientCountryInputRef?.current?.value ?? '',
        postalCode: formRefs.postalCodeInputRef?.current?.value ?? '',
        street: formRefs.streetAddressInputRef?.current?.value ?? ''
      },
      client: {
        name: formRefs.clientNameInputRef?.current?.value ?? '',
        email: formRefs.clientEmailInputRef?.current?.value ?? '',
        postalCode: formRefs.clientPostalCodeInputRef?.current?.value ?? '',
        street: formRefs.clientStreetAddressInputRef?.current?.value ?? '',
        city: formRefs.clientCityInputRef?.current?.value ?? '',
        country: formRefs.clientCountryInputRef?.current?.value ?? ''
      },
      items: itemCounter,
      status: options.draft ? 'draft' : 'pending'
    };
    mutate([...invoiceDataSWR, newInvoice], { revalidate: false });
    clearForm();
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AnimatePresence>{invoiceFormVisbility && <InvoiceForm {...formProps} />}</AnimatePresence>
      <Nav />

      <main
        className={`flex w-full flex-col items-center bg-slate-100 ${
          invoiceFormVisbility && 'h-screen overflow-hidden'
        }`}>
        <div className="flex max-w-4xl flex-col py-12">
          <Header mountForm={mountForm} invoiceItemLength={invoiceDataSWR?.length} />
          <InvoiceList invoiceData={invoiceDataSWR} />
        </div>
      </main>
    </div>
  );
};

export default Home;
