import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Header from '../components/header';
import InvoiceList from '../components/InvoiceList';
import Nav from '../components/nav';

import { invoiceData } from '../data/invoice-data';

const Home: NextPage = () => {
  const invoiceItemLength = invoiceData.length;
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen grow flex-row items-center justify-between bg-slate-200">
        <Nav />
        <main className="flex min-h-screen w-full justify-center px-12 py-12">
          <div className="w-full max-w-4xl">
            <Header invoiceItemLength={invoiceItemLength} />
            <InvoiceList invoiceData={invoiceData} />
          </div>
        </main>
      </div>

      <footer></footer>
    </div>
  );
};

export default Home;
